library(ggplot2)
library(ggrepel)
library(cowplot)
library(reshape2)

setwd("D:/Assembly-Benchmarking/Fig2-PrecisionSensitivity")

Sub40k <- read.csv("sub40k/Sub40k_MainSuppA.csv", sep = ";", header = T)
Sub150k <- read.csv("sub150k/Sub150k_MainSuppB.csv", sep = ";", header = T)

#sub40k - GFF
inpt40 <- melt(subset(Sub40k, Evaluator == "GFFcompare"),id.vars=c("Dataset","Assembly","Method","Tool","Evaluator"))
inpt40$Dataset <- factor(inpt40$Dataset, levels=c("LSK114_SIRVs","LSK114_sequins"))

Prec40 <- subset(inpt40,variable=="Precision")
Rec40 <- subset(inpt40,variable=="Sensitivity")
F140 <- subset(inpt40,variable=="F1")
Prec40_DN <- subset(Prec40,Method=="De novo" | Method=="RawReads")
Prec40_G <- subset(Prec40,Method=="Guided" | Method=="RawReads")
Prec40_AI <- subset(Prec40,Method=="Ab initio" | Method=="RawReads")
Rec40_DN <- subset(Rec40,Method=="De novo" | Method=="RawReads")
Rec40_G <- subset(Rec40,Method=="Guided" | Method=="RawReads")
Rec40_AI <- subset(Rec40,Method=="Ab initio" | Method=="RawReads")
F140_DN <- subset(F140,Method=="De novo" | Method=="RawReads")
F140_G <- subset(F140,Method=="Guided" | Method=="RawReads")
F140_AI <- subset(F140,Method=="Ab initio" | Method=="RawReads")

Prec40_guided <- ggplot(Prec40_G, aes(fill=Tool, x=Dataset, y=value, group=Assembly)) + geom_point(aes(colour = Tool, shape = Method)) + geom_line(aes(colour = Tool, linetype = Assembly), data = ~ subset(., Assembly != "TALON_reco")) + geom_line(aes(colour = Tool, linetype = Assembly), data = ~ subset(., Assembly == "TALON_reco")) +  scale_linetype_manual(values = c("Control"="solid","Bambu" = "solid", "FLAIR" = "solid", "isoQuant" = "solid", "TALON" = "solid", "FLAMES" = "solid", "Mandalorion" = "solid", "Stringtie2" = "solid", "TALON_reco" = "longdash")) + ylim(0,1) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = c("Bambu" = "brown","FLAIR"="violet","isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","RATTLE"="springgreen2","RNAbloom"="coral2","RNAbloom2"="orangered3","Stringtie2"="palegreen4","TALON"="wheat2","FLAMES"="blue2","Mandalorion"="darkgoldenrod1"))  + scale_shape_manual(values=c(15,9)) + xlab("") + ylab("Precision")
Prec40_DeNovo <- ggplot(Prec40_DN, aes(fill=Tool, x=Dataset, y=value, group=Assembly)) + geom_point(aes(colour = Tool, shape = Method)) + geom_line(aes(colour = Tool)) +  ylim(0,1) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = c("Bambu" = "brown","FLAIR"="violet","isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","RATTLE"="springgreen2","RNAbloom"="coral2","RNAbloom2"="orangered3","Stringtie2"="palegreen4","TALON"="wheat2","FLAMES"="blue2","Mandalorion"="darkgoldenrod1")) + scale_shape_manual(values=c(17,9)) + xlab("") + ylab("Precision")
Prec40_AbInitio <- ggplot(Prec40_AI, aes(fill=Tool, x=Dataset, y=value, group=Assembly)) + geom_point(aes(colour = Tool, shape = Method)) + geom_line(aes(colour = Tool)) +  ylim(0,1) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = c("Bambu" = "brown","FLAIR"="violet","isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","RATTLE"="springgreen2","RNAbloom"="coral2","RNAbloom2"="orangered3","Stringtie2"="palegreen4","TALON"="wheat2","FLAMES"="blue2","Mandalorion"="darkgoldenrod1")) + scale_shape_manual(values=c(19,9)) + xlab("") + ylab("Precision")

Rec40_guided <- ggplot(Rec40_G, aes(fill=Tool, x=Dataset, y=value, group=Assembly)) + geom_point(aes(colour = Tool, shape = Method)) + geom_line(aes(colour = Tool, linetype = Assembly), data = ~ subset(., Assembly != "TALON_reco")) + geom_line(aes(colour = Tool, linetype = Assembly), data = ~ subset(., Assembly == "TALON_reco")) +  scale_linetype_manual(values = c("Control"="solid","Bambu" = "solid", "FLAIR" = "solid", "isoQuant" = "solid", "TALON" = "solid", "FLAMES" = "solid", "Mandalorion" = "solid", "Stringtie2" = "solid", "TALON_reco" = "longdash")) +  ylim(0,1) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = c("Bambu" = "brown","FLAIR"="violet","isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","RATTLE"="springgreen2","RNAbloom"="coral2","RNAbloom2"="orangered3","Stringtie2"="palegreen4","TALON"="wheat2","FLAMES"="blue2","Mandalorion"="darkgoldenrod1")) + scale_shape_manual(values=c(15,9)) + xlab("") + ylab("Sensitivity")
Rec40_DeNovo <- ggplot(Rec40_DN, aes(fill=Tool, x=Dataset, y=value, group=Assembly)) + geom_point(aes(colour = Tool, shape = Method)) + geom_line(aes(colour = Tool)) +  ylim(0,1) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = c("Bambu" = "brown","FLAIR"="violet","isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","RATTLE"="springgreen2","RNAbloom"="coral2","RNAbloom2"="orangered3","Stringtie2"="palegreen4","TALON"="wheat2","FLAMES"="blue2","Mandalorion"="darkgoldenrod1")) + scale_shape_manual(values=c(17,9)) + xlab("") + ylab("Sensitivity")
Rec40_AbInitio <- ggplot(Rec40_AI, aes(fill=Tool, x=Dataset, y=value, group=Assembly)) + geom_point(aes(colour = Tool, shape = Method)) + geom_line(aes(colour = Tool)) +  ylim(0,1) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = c("Bambu" = "brown","FLAIR"="violet","isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","RATTLE"="springgreen2","RNAbloom"="coral2","RNAbloom2"="orangered3","Stringtie2"="palegreen4","TALON"="wheat2","FLAMES"="blue2","Mandalorion"="darkgoldenrod1")) + scale_shape_manual(values=c(19,9)) + xlab("") + ylab("Sensitivity")

F140_guided <- ggplot(F140_G, aes(fill=Tool, x=Dataset, y=value, group=Assembly)) + geom_point(aes(colour = Tool, shape = Method)) + geom_line(aes(colour = Tool, linetype = Assembly), data = ~ subset(., Assembly != "TALON_reco")) + geom_line(aes(colour = Tool, linetype = Assembly), data = ~ subset(., Assembly == "TALON_reco")) +  scale_linetype_manual(values = c("Control"="solid","Bambu" = "solid", "FLAIR" = "solid", "isoQuant" = "solid", "TALON" = "solid", "FLAMES" = "solid", "Mandalorion" = "solid", "Stringtie2" = "solid", "TALON_reco" = "longdash")) +  ylim(0,1) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = c("Bambu" = "brown","FLAIR"="violet","isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","RATTLE"="springgreen2","RNAbloom"="coral2","RNAbloom2"="orangered3","Stringtie2"="palegreen4","TALON"="wheat2","FLAMES"="blue2","Mandalorion"="darkgoldenrod1")) + scale_shape_manual(values=c(15,9)) + xlab("") + ylab("F1")
F140_DeNovo <- ggplot(F140_DN, aes(fill=Tool, x=Dataset, y=value, group=Assembly)) + geom_point(aes(colour = Tool, shape = Method)) + geom_line(aes(colour = Tool)) +  ylim(0,1) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = c("Bambu" = "brown","FLAIR"="violet","isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","RATTLE"="springgreen2","RNAbloom"="coral2","RNAbloom2"="orangered3","Stringtie2"="palegreen4","TALON"="wheat2","FLAMES"="blue2","Mandalorion"="darkgoldenrod1")) + scale_shape_manual(values=c(17,9)) + xlab("") + ylab("F1")
F140_AbInitio <- ggplot(F140_AI, aes(fill=Tool, x=Dataset, y=value, group=Assembly)) + geom_point(aes(colour = Tool, shape = Method)) + geom_line(aes(colour = Tool)) +  ylim(0,1) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = c("Bambu" = "brown","FLAIR"="violet","isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","RATTLE"="springgreen2","RNAbloom"="coral2","RNAbloom2"="orangered3","Stringtie2"="palegreen4","TALON"="wheat2","FLAMES"="blue2","Mandalorion"="darkgoldenrod1")) + scale_shape_manual(values=c(19,9)) + xlab("") + ylab("F1")

#legend <- plot_grid(get_legend(Prec40_guided),get_legend(Prec40_DeNovo),get_legend(Prec40_AbInitio),ncol=1)

Prec40_DeNovo <- Prec40_DeNovo + theme(legend.position = "none")
Prec40_guided <- Prec40_guided + theme(legend.position = "none")
Prec40_AbInitio <- Prec40_AbInitio + theme(legend.position = "none")
Rec40_DeNovo <- Rec40_DeNovo + theme(legend.position = "none")
Rec40_guided <- Rec40_guided + theme(legend.position = "none")
Rec40_AbInitio <- Rec40_AbInitio + theme(legend.position = "none")
F140_DeNovo <- F140_DeNovo + theme(legend.position = "none")
F140_guided <- F140_guided + theme(legend.position = "none")
F140_AbInitio <- F140_AbInitio + theme(legend.position = "none")

#sub40k - SQ3
SQ3inpt40 <- melt(subset(Sub40k, Evaluator == "SQANTI3"),id.vars=c("Dataset","Assembly","Method","Tool","Evaluator"))
SQ3inpt40$Dataset <- factor(SQ3inpt40$Dataset, levels=c("LSK114_SIRVs","LSK114_sequins"))

SQ3Prec40 <- subset(SQ3inpt40,variable=="Precision")
SQ3Rec40 <- subset(SQ3inpt40,variable=="Sensitivity")
SQ3F140 <- subset(SQ3inpt40,variable=="F1")
SQ3Prec40_DN <- subset(SQ3Prec40,Method=="De novo" | Method=="RawReads")
SQ3Prec40_G <- subset(SQ3Prec40,Method=="Guided" | Method=="RawReads")
SQ3Prec40_AI <- subset(SQ3Prec40,Method=="Ab initio" | Method=="RawReads")
SQ3Rec40_DN <- subset(SQ3Rec40,Method=="De novo" | Method=="RawReads")
SQ3Rec40_G <- subset(SQ3Rec40,Method=="Guided" | Method=="RawReads")
SQ3Rec40_AI <- subset(SQ3Rec40,Method=="Ab initio" | Method=="RawReads")
SQ3F140_DN <- subset(SQ3F140,Method=="De novo" | Method=="RawReads")
SQ3F140_G <- subset(SQ3F140,Method=="Guided" | Method=="RawReads")
SQ3F140_AI <- subset(SQ3F140,Method=="Ab initio" | Method=="RawReads")

SQ3Prec40_guided <- ggplot(SQ3Prec40_G, aes(fill=Tool, x=Dataset, y=value, group=Assembly)) + geom_point(aes(colour = Tool, shape = Method)) + geom_line(aes(colour = Tool, linetype = Assembly), data = ~ subset(., Assembly != "TALON_reco")) + geom_line(aes(colour = Tool, linetype = Assembly), data = ~ subset(., Assembly == "TALON_reco")) +  scale_linetype_manual(values = c("Control"="solid","Bambu" = "solid", "FLAIR" = "solid", "isoQuant" = "solid", "TALON" = "solid", "FLAMES" = "solid", "Mandalorion" = "solid", "Stringtie2" = "solid", "TALON_reco" = "longdash")) + ylim(0,1) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = c("Bambu" = "brown","FLAIR"="violet","isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","RATTLE"="springgreen2","RNAbloom"="coral2","RNAbloom2"="orangered3","Stringtie2"="palegreen4","TALON"="wheat2","FLAMES"="blue2","Mandalorion"="darkgoldenrod1"))  + scale_shape_manual(values=c(15,9)) + xlab("") + ylab("Precision") + theme(legend.position = "none")
SQ3Prec40_DeNovo <- ggplot(SQ3Prec40_DN, aes(fill=Tool, x=Dataset, y=value, group=Assembly)) + geom_point(aes(colour = Tool, shape = Method)) + geom_line(aes(colour = Tool)) +  ylim(0,1) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = c("Bambu" = "brown","FLAIR"="violet","isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","RATTLE"="springgreen2","RNAbloom"="coral2","RNAbloom2"="orangered3","Stringtie2"="palegreen4","TALON"="wheat2","FLAMES"="blue2","Mandalorion"="darkgoldenrod1")) + scale_shape_manual(values=c(17,9)) + xlab("") + ylab("Precision") + theme(legend.position = "none")
SQ3Prec40_AbInitio <- ggplot(SQ3Prec40_AI, aes(fill=Tool, x=Dataset, y=value, group=Assembly)) + geom_point(aes(colour = Tool, shape = Method)) + geom_line(aes(colour = Tool)) +  ylim(0,1) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = c("Bambu" = "brown","FLAIR"="violet","isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","RATTLE"="springgreen2","RNAbloom"="coral2","RNAbloom2"="orangered3","Stringtie2"="palegreen4","TALON"="wheat2","FLAMES"="blue2","Mandalorion"="darkgoldenrod1")) + scale_shape_manual(values=c(19,9)) + xlab("") + ylab("Precision") + theme(legend.position = "none")

SQ3Rec40_guided <- ggplot(SQ3Rec40_G, aes(fill=Tool, x=Dataset, y=value, group=Assembly)) + geom_point(aes(colour = Tool, shape = Method)) + geom_line(aes(colour = Tool, linetype = Assembly), data = ~ subset(., Assembly != "TALON_reco")) + geom_line(aes(colour = Tool, linetype = Assembly), data = ~ subset(., Assembly == "TALON_reco")) +  scale_linetype_manual(values = c("Control"="solid","Bambu" = "solid", "FLAIR" = "solid", "isoQuant" = "solid", "TALON" = "solid", "FLAMES" = "solid", "Mandalorion" = "solid", "Stringtie2" = "solid", "TALON_reco" = "longdash")) +  ylim(0,1) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = c("Bambu" = "brown","FLAIR"="violet","isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","RATTLE"="springgreen2","RNAbloom"="coral2","RNAbloom2"="orangered3","Stringtie2"="palegreen4","TALON"="wheat2","FLAMES"="blue2","Mandalorion"="darkgoldenrod1")) + scale_shape_manual(values=c(15,9)) + xlab("") + ylab("Sensitivity") + theme(legend.position = "none")
SQ3Rec40_DeNovo <- ggplot(SQ3Rec40_DN, aes(fill=Tool, x=Dataset, y=value, group=Assembly)) + geom_point(aes(colour = Tool, shape = Method)) + geom_line(aes(colour = Tool)) +  ylim(0,1) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = c("Bambu" = "brown","FLAIR"="violet","isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","RATTLE"="springgreen2","RNAbloom"="coral2","RNAbloom2"="orangered3","Stringtie2"="palegreen4","TALON"="wheat2","FLAMES"="blue2","Mandalorion"="darkgoldenrod1")) + scale_shape_manual(values=c(17,9)) + xlab("") + ylab("Sensitivity") + theme(legend.position = "none")
SQ3Rec40_AbInitio <- ggplot(SQ3Rec40_AI, aes(fill=Tool, x=Dataset, y=value, group=Assembly)) + geom_point(aes(colour = Tool, shape = Method)) + geom_line(aes(colour = Tool)) +  ylim(0,1) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = c("Bambu" = "brown","FLAIR"="violet","isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","RATTLE"="springgreen2","RNAbloom"="coral2","RNAbloom2"="orangered3","Stringtie2"="palegreen4","TALON"="wheat2","FLAMES"="blue2","Mandalorion"="darkgoldenrod1")) + scale_shape_manual(values=c(19,9)) + xlab("") + ylab("Sensitivity") + theme(legend.position = "none")

SQ3F140_guided <- ggplot(SQ3F140_G, aes(fill=Tool, x=Dataset, y=value, group=Assembly)) + geom_point(aes(colour = Tool, shape = Method)) + geom_line(aes(colour = Tool, linetype = Assembly), data = ~ subset(., Assembly != "TALON_reco")) + geom_line(aes(colour = Tool, linetype = Assembly), data = ~ subset(., Assembly == "TALON_reco")) +  scale_linetype_manual(values = c("Control"="solid","Bambu" = "solid", "FLAIR" = "solid", "isoQuant" = "solid", "TALON" = "solid", "FLAMES" = "solid", "Mandalorion" = "solid", "Stringtie2" = "solid", "TALON_reco" = "longdash")) +  ylim(0,1) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = c("Bambu" = "brown","FLAIR"="violet","isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","RATTLE"="springgreen2","RNAbloom"="coral2","RNAbloom2"="orangered3","Stringtie2"="palegreen4","TALON"="wheat2","FLAMES"="blue2","Mandalorion"="darkgoldenrod1")) + scale_shape_manual(values=c(15,9)) + xlab("") + ylab("F1") + theme(legend.position = "none")
SQ3F140_DeNovo <- ggplot(SQ3F140_DN, aes(fill=Tool, x=Dataset, y=value, group=Assembly)) + geom_point(aes(colour = Tool, shape = Method)) + geom_line(aes(colour = Tool)) +  ylim(0,1) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = c("Bambu" = "brown","FLAIR"="violet","isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","RATTLE"="springgreen2","RNAbloom"="coral2","RNAbloom2"="orangered3","Stringtie2"="palegreen4","TALON"="wheat2","FLAMES"="blue2","Mandalorion"="darkgoldenrod1")) + scale_shape_manual(values=c(17,9)) + xlab("") + ylab("F1") + theme(legend.position = "none")
SQ3F140_AbInitio <- ggplot(SQ3F140_AI, aes(fill=Tool, x=Dataset, y=value, group=Assembly)) + geom_point(aes(colour = Tool, shape = Method)) + geom_line(aes(colour = Tool)) +  ylim(0,1) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = c("Bambu" = "brown","FLAIR"="violet","isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","RATTLE"="springgreen2","RNAbloom"="coral2","RNAbloom2"="orangered3","Stringtie2"="palegreen4","TALON"="wheat2","FLAMES"="blue2","Mandalorion"="darkgoldenrod1")) + scale_shape_manual(values=c(19,9)) + xlab("") + ylab("F1") + theme(legend.position = "none")



#sub150k - GFF
inpt150 <- melt(subset(Sub150k, Evaluator == "GFFcompare"),id.vars=c("Dataset","Assembly","Method","Tool","Evaluator"))
inpt150$Dataset <- factor(inpt150$Dataset, levels=c("LSK109_sequins","LSK114_sequins","RNA002_sequins","RNA004_sequins"))

Prec150 <- subset(inpt150,variable=="Precision")
Rec150 <- subset(inpt150,variable=="Sensitivity")
F1150 <- subset(inpt150,variable=="F1")
Prec150_DN <- subset(Prec150,Method=="De novo" | Method=="RawReads")
Prec150_G <- subset(Prec150,Method=="Guided" | Method=="RawReads")
Prec150_AI <- subset(Prec150,Method=="Ab initio" | Method=="RawReads")
Rec150_DN <- subset(Rec150,Method=="De novo" | Method=="RawReads")
Rec150_G <- subset(Rec150,Method=="Guided" | Method=="RawReads")
Rec150_AI <- subset(Rec150,Method=="Ab initio" | Method=="RawReads")
F1150_DN <- subset(F1150,Method=="De novo" | Method=="RawReads")
F1150_G <- subset(F1150,Method=="Guided" | Method=="RawReads")
F1150_AI <- subset(F1150,Method=="Ab initio" | Method=="RawReads")

Prec150_guided <- ggplot(Prec150_G, aes(fill=Tool, x=Dataset, y=value, group=Assembly)) + geom_point(aes(colour = Tool, shape = Method)) + geom_line(aes(colour = Tool, linetype = Assembly), data = ~ subset(., Assembly != "TALON_reco")) + geom_line(aes(colour = Tool, linetype = Assembly), data = ~ subset(., Assembly == "TALON_reco")) +  scale_linetype_manual(values = c("Control"="solid","Bambu" = "solid", "FLAIR" = "solid", "isoQuant" = "solid", "TALON" = "solid", "FLAMES" = "solid", "Mandalorion" = "solid", "Stringtie2" = "solid", "TALON_reco" = "longdash")) +  ylim(0,1) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = c("Bambu" = "brown","FLAIR"="violet","isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","RATTLE"="springgreen2","RNAbloom"="coral2","RNAbloom2"="orangered3","Stringtie2"="palegreen4","TALON"="wheat2","FLAMES"="blue2","Mandalorion"="darkgoldenrod1")) + scale_shape_manual(values=c(15,9)) + xlab("") + ylab("Precision")
Prec150_DeNovo <- ggplot(Prec150_DN, aes(fill=Tool, x=Dataset, y=value, group=Assembly)) + geom_point(aes(colour = Tool, shape = Method)) + geom_line(aes(colour = Tool)) +  ylim(0,1) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = c("Bambu" = "brown","FLAIR"="violet","isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","RATTLE"="springgreen2","RNAbloom"="coral2","RNAbloom2"="orangered3","Stringtie2"="palegreen4","TALON"="wheat2","FLAMES"="blue2","Mandalorion"="darkgoldenrod1")) + scale_shape_manual(values=c(17,9)) + xlab("") + ylab("Precision")
Prec150_AbInitio <- ggplot(Prec150_AI, aes(fill=Tool, x=Dataset, y=value, group=Assembly)) + geom_point(aes(colour = Tool, shape = Method)) + geom_line(aes(colour = Tool)) +  ylim(0,1) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = c("Bambu" = "brown","FLAIR"="violet","isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","RATTLE"="springgreen2","RNAbloom"="coral2","RNAbloom2"="orangered3","Stringtie2"="palegreen4","TALON"="wheat2","FLAMES"="blue2","Mandalorion"="darkgoldenrod1")) + scale_shape_manual(values=c(19,9)) + xlab("") + ylab("Precision")

Rec150_guided <- ggplot(Rec150_G, aes(fill=Tool, x=Dataset, y=value, group=Assembly)) + geom_point(aes(colour = Tool, shape = Method)) + geom_line(aes(colour = Tool, linetype = Assembly), data = ~ subset(., Assembly != "TALON_reco")) + geom_line(aes(colour = Tool, linetype = Assembly), data = ~ subset(., Assembly == "TALON_reco")) +  scale_linetype_manual(values = c("Control"="solid","Bambu" = "solid", "FLAIR" = "solid", "isoQuant" = "solid", "TALON" = "solid", "FLAMES" = "solid", "Mandalorion" = "solid", "Stringtie2" = "solid", "TALON_reco" = "longdash")) +  ylim(0,1) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = c("Bambu" = "brown","FLAIR"="violet","isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","RATTLE"="springgreen2","RNAbloom"="coral2","RNAbloom2"="orangered3","Stringtie2"="palegreen4","TALON"="wheat2","FLAMES"="blue2","Mandalorion"="darkgoldenrod1")) + scale_shape_manual(values=c(15,9)) + xlab("") + ylab("Sensitivity")
Rec150_DeNovo <- ggplot(Rec150_DN, aes(fill=Tool, x=Dataset, y=value, group=Assembly)) + geom_point(aes(colour = Tool, shape = Method)) + geom_line(aes(colour = Tool)) +  ylim(0,1) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = c("Bambu" = "brown","FLAIR"="violet","isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","RATTLE"="springgreen2","RNAbloom"="coral2","RNAbloom2"="orangered3","Stringtie2"="palegreen4","TALON"="wheat2","FLAMES"="blue2","Mandalorion"="darkgoldenrod1")) + scale_shape_manual(values=c(17,9)) + xlab("") + ylab("Sensitivity")
Rec150_AbInitio <- ggplot(Rec150_AI, aes(fill=Tool, x=Dataset, y=value, group=Assembly)) + geom_point(aes(colour = Tool, shape = Method)) + geom_line(aes(colour = Tool)) +  ylim(0,1) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = c("Bambu" = "brown","FLAIR"="violet","isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","RATTLE"="springgreen2","RNAbloom"="coral2","RNAbloom2"="orangered3","Stringtie2"="palegreen4","TALON"="wheat2","FLAMES"="blue2","Mandalorion"="darkgoldenrod1")) + scale_shape_manual(values=c(19,9)) + xlab("") + ylab("Sensitivity")

F1150_guided <- ggplot(F1150_G, aes(fill=Tool, x=Dataset, y=value, group=Assembly)) + geom_point(aes(colour = Tool, shape = Method)) + geom_line(aes(colour = Tool, linetype = Assembly), data = ~ subset(., Assembly != "TALON_reco")) + geom_line(aes(colour = Tool, linetype = Assembly), data = ~ subset(., Assembly == "TALON_reco")) +  scale_linetype_manual(values = c("Control"="solid","Bambu" = "solid", "FLAIR" = "solid", "isoQuant" = "solid", "TALON" = "solid", "FLAMES" = "solid", "Mandalorion" = "solid", "Stringtie2" = "solid", "TALON_reco" = "longdash")) +  ylim(0,1) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = c("Bambu" = "brown","FLAIR"="violet","isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","RATTLE"="springgreen2","RNAbloom"="coral2","RNAbloom2"="orangered3","Stringtie2"="palegreen4","TALON"="wheat2","FLAMES"="blue2","Mandalorion"="darkgoldenrod1")) + scale_shape_manual(values=c(15,9)) + xlab("") + ylab("F1")
F1150_DeNovo <- ggplot(F1150_DN, aes(fill=Tool, x=Dataset, y=value, group=Assembly)) + geom_point(aes(colour = Tool, shape = Method)) + geom_line(aes(colour = Tool)) +  ylim(0,1) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = c("Bambu" = "brown","FLAIR"="violet","isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","RATTLE"="springgreen2","RNAbloom"="coral2","RNAbloom2"="orangered3","Stringtie2"="palegreen4","TALON"="wheat2","FLAMES"="blue2","Mandalorion"="darkgoldenrod1")) + scale_shape_manual(values=c(17,9)) + xlab("") + ylab("F1")
F1150_AbInitio <- ggplot(F1150_AI, aes(fill=Tool, x=Dataset, y=value, group=Assembly)) + geom_point(aes(colour = Tool, shape = Method)) + geom_line(aes(colour = Tool)) +  ylim(0,1) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = c("Bambu" = "brown","FLAIR"="violet","isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","RATTLE"="springgreen2","RNAbloom"="coral2","RNAbloom2"="orangered3","Stringtie2"="palegreen4","TALON"="wheat2","FLAMES"="blue2","Mandalorion"="darkgoldenrod1")) + scale_shape_manual(values=c(19,9)) + xlab("") + ylab("F1")

#legend <- plot_grid(get_legend(Prec150_guided),get_legend(Prec150_DeNovo),get_legend(Prec150_AbInitio),ncol=1)

Prec150_DeNovo <- Prec150_DeNovo + theme(legend.position = "none")
Prec150_guided <- Prec150_guided + theme(legend.position = "none")
Prec150_AbInitio <- Prec150_AbInitio + theme(legend.position = "none")
Rec150_DeNovo <- Rec150_DeNovo + theme(legend.position = "none")
Rec150_guided <- Rec150_guided + theme(legend.position = "none")
Rec150_AbInitio <- Rec150_AbInitio + theme(legend.position = "none")
F1150_DeNovo <- F1150_DeNovo + theme(legend.position = "none")
F1150_guided <- F1150_guided + theme(legend.position = "none")
F1150_AbInitio <- F1150_AbInitio + theme(legend.position = "none")

#sub150k - SQ3
SQ3inpt150 <- melt(subset(Sub150k, Evaluator == "SQANTI3"),id.vars=c("Dataset","Assembly","Method","Tool","Evaluator"))
SQ3inpt150$Dataset <- factor(SQ3inpt150$Dataset, levels=c("LSK109_sequins","LSK114_sequins","RNA002_sequins","RNA004_sequins"))

SQ3Prec150 <- subset(SQ3inpt150,variable=="Precision")
SQ3Rec150 <- subset(SQ3inpt150,variable=="Sensitivity")
SQ3F1150 <- subset(SQ3inpt150,variable=="F1")
SQ3Prec150_DN <- subset(SQ3Prec150,Method=="De novo" | Method=="RawReads")
SQ3Prec150_G <- subset(SQ3Prec150,Method=="Guided" | Method=="RawReads")
SQ3Prec150_AI <- subset(SQ3Prec150,Method=="Ab initio" | Method=="RawReads")
SQ3Rec150_DN <- subset(SQ3Rec150,Method=="De novo" | Method=="RawReads")
SQ3Rec150_G <- subset(SQ3Rec150,Method=="Guided" | Method=="RawReads")
SQ3Rec150_AI <- subset(SQ3Rec150,Method=="Ab initio" | Method=="RawReads")
SQ3F1150_DN <- subset(SQ3F1150,Method=="De novo" | Method=="RawReads")
SQ3F1150_G <- subset(SQ3F1150,Method=="Guided" | Method=="RawReads")
SQ3F1150_AI <- subset(SQ3F1150,Method=="Ab initio" | Method=="RawReads")

SQ3Prec150_guided <- ggplot(SQ3Prec150_G, aes(fill=Tool, x=Dataset, y=value, group=Assembly)) + geom_point(aes(colour = Tool, shape = Method)) + geom_line(aes(colour = Tool, linetype = Assembly), data = ~ subset(., Assembly != "TALON_reco")) + geom_line(aes(colour = Tool, linetype = Assembly), data = ~ subset(., Assembly == "TALON_reco")) +  scale_linetype_manual(values = c("Control"="solid","Bambu" = "solid", "FLAIR" = "solid", "isoQuant" = "solid", "TALON" = "solid", "FLAMES" = "solid", "Mandalorion" = "solid", "Stringtie2" = "solid", "TALON_reco" = "longdash")) +  ylim(0,1) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = c("Bambu" = "brown","FLAIR"="violet","isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","RATTLE"="springgreen2","RNAbloom"="coral2","RNAbloom2"="orangered3","Stringtie2"="palegreen4","TALON"="wheat2","FLAMES"="blue2","Mandalorion"="darkgoldenrod1")) + scale_shape_manual(values=c(15,9)) + xlab("") + ylab("Precision") + theme(legend.position = "none")
SQ3Prec150_DeNovo <- ggplot(SQ3Prec150_DN, aes(fill=Tool, x=Dataset, y=value, group=Assembly)) + geom_point(aes(colour = Tool, shape = Method)) + geom_line(aes(colour = Tool)) +  ylim(0,1) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = c("Bambu" = "brown","FLAIR"="violet","isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","RATTLE"="springgreen2","RNAbloom"="coral2","RNAbloom2"="orangered3","Stringtie2"="palegreen4","TALON"="wheat2","FLAMES"="blue2","Mandalorion"="darkgoldenrod1")) + scale_shape_manual(values=c(17,9)) + xlab("") + ylab("Precision") + theme(legend.position = "none")
SQ3Prec150_AbInitio <- ggplot(SQ3Prec150_AI, aes(fill=Tool, x=Dataset, y=value, group=Assembly)) + geom_point(aes(colour = Tool, shape = Method)) + geom_line(aes(colour = Tool)) +  ylim(0,1) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = c("Bambu" = "brown","FLAIR"="violet","isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","RATTLE"="springgreen2","RNAbloom"="coral2","RNAbloom2"="orangered3","Stringtie2"="palegreen4","TALON"="wheat2","FLAMES"="blue2","Mandalorion"="darkgoldenrod1")) + scale_shape_manual(values=c(19,9)) + xlab("") + ylab("Precision") + theme(legend.position = "none")

SQ3Rec150_guided <- ggplot(SQ3Rec150_G, aes(fill=Tool, x=Dataset, y=value, group=Assembly)) + geom_point(aes(colour = Tool, shape = Method)) + geom_line(aes(colour = Tool, linetype = Assembly), data = ~ subset(., Assembly != "TALON_reco")) + geom_line(aes(colour = Tool, linetype = Assembly), data = ~ subset(., Assembly == "TALON_reco")) +  scale_linetype_manual(values = c("Control"="solid","Bambu" = "solid", "FLAIR" = "solid", "isoQuant" = "solid", "TALON" = "solid", "FLAMES" = "solid", "Mandalorion" = "solid", "Stringtie2" = "solid", "TALON_reco" = "longdash")) +  ylim(0,1) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = c("Bambu" = "brown","FLAIR"="violet","isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","RATTLE"="springgreen2","RNAbloom"="coral2","RNAbloom2"="orangered3","Stringtie2"="palegreen4","TALON"="wheat2","FLAMES"="blue2","Mandalorion"="darkgoldenrod1")) + scale_shape_manual(values=c(15,9)) + xlab("") + ylab("Sensitivity") + theme(legend.position = "none")
SQ3Rec150_DeNovo <- ggplot(SQ3Rec150_DN, aes(fill=Tool, x=Dataset, y=value, group=Assembly)) + geom_point(aes(colour = Tool, shape = Method)) + geom_line(aes(colour = Tool)) +  ylim(0,1) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = c("Bambu" = "brown","FLAIR"="violet","isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","RATTLE"="springgreen2","RNAbloom"="coral2","RNAbloom2"="orangered3","Stringtie2"="palegreen4","TALON"="wheat2","FLAMES"="blue2","Mandalorion"="darkgoldenrod1")) + scale_shape_manual(values=c(17,9)) + xlab("") + ylab("Sensitivity") + theme(legend.position = "none")
SQ3Rec150_AbInitio <- ggplot(SQ3Rec150_AI, aes(fill=Tool, x=Dataset, y=value, group=Assembly)) + geom_point(aes(colour = Tool, shape = Method)) + geom_line(aes(colour = Tool)) +  ylim(0,1) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = c("Bambu" = "brown","FLAIR"="violet","isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","RATTLE"="springgreen2","RNAbloom"="coral2","RNAbloom2"="orangered3","Stringtie2"="palegreen4","TALON"="wheat2","FLAMES"="blue2","Mandalorion"="darkgoldenrod1")) + scale_shape_manual(values=c(19,9)) + xlab("") + ylab("Sensitivity") + theme(legend.position = "none")

SQ3F1150_guided <- ggplot(SQ3F1150_G, aes(fill=Tool, x=Dataset, y=value, group=Assembly)) + geom_point(aes(colour = Tool, shape = Method)) + geom_line(aes(colour = Tool, linetype = Assembly), data = ~ subset(., Assembly != "TALON_reco")) + geom_line(aes(colour = Tool, linetype = Assembly), data = ~ subset(., Assembly == "TALON_reco")) +  scale_linetype_manual(values = c("Control"="solid","Bambu" = "solid", "FLAIR" = "solid", "isoQuant" = "solid", "TALON" = "solid", "FLAMES" = "solid", "Mandalorion" = "solid", "Stringtie2" = "solid", "TALON_reco" = "longdash")) +  ylim(0,1) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = c("Bambu" = "brown","FLAIR"="violet","isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","RATTLE"="springgreen2","RNAbloom"="coral2","RNAbloom2"="orangered3","Stringtie2"="palegreen4","TALON"="wheat2","FLAMES"="blue2","Mandalorion"="darkgoldenrod1")) + scale_shape_manual(values=c(15,9)) + xlab("") + ylab("F1") + theme(legend.position = "none")
SQ3F1150_DeNovo <- ggplot(SQ3F1150_DN, aes(fill=Tool, x=Dataset, y=value, group=Assembly)) + geom_point(aes(colour = Tool, shape = Method)) + geom_line(aes(colour = Tool)) +  ylim(0,1) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = c("Bambu" = "brown","FLAIR"="violet","isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","RATTLE"="springgreen2","RNAbloom"="coral2","RNAbloom2"="orangered3","Stringtie2"="palegreen4","TALON"="wheat2","FLAMES"="blue2","Mandalorion"="darkgoldenrod1")) + scale_shape_manual(values=c(17,9)) + xlab("") + ylab("F1") + theme(legend.position = "none")
SQ3F1150_AbInitio <- ggplot(SQ3F1150_AI, aes(fill=Tool, x=Dataset, y=value, group=Assembly)) + geom_point(aes(colour = Tool, shape = Method)) + geom_line(aes(colour = Tool)) +  ylim(0,1) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = c("Bambu" = "brown","FLAIR"="violet","isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","RATTLE"="springgreen2","RNAbloom"="coral2","RNAbloom2"="orangered3","Stringtie2"="palegreen4","TALON"="wheat2","FLAMES"="blue2","Mandalorion"="darkgoldenrod1")) + scale_shape_manual(values=c(19,9)) + xlab("") + ylab("F1") + theme(legend.position = "none")

#Supp figure
plot_grid(Prec40_guided,Prec40_DeNovo,Prec40_AbInitio,Prec150_guided,Prec150_DeNovo,Prec150_AbInitio,Rec40_guided,Rec40_DeNovo,Rec40_AbInitio,Rec150_guided,Rec150_DeNovo,Rec150_AbInitio,F140_guided,F140_DeNovo,F140_AbInitio,F1150_guided,F1150_DeNovo,F1150_AbInitio,SQ3Prec40_guided,SQ3Prec40_DeNovo,SQ3Prec40_AbInitio,SQ3Prec150_guided,SQ3Prec150_DeNovo,SQ3Prec150_AbInitio,SQ3Rec40_guided,SQ3Rec40_DeNovo,SQ3Rec40_AbInitio,SQ3Rec150_guided,SQ3Rec150_DeNovo,SQ3Rec150_AbInitio,SQ3F140_guided,SQ3F140_DeNovo,SQ3F140_AbInitio,SQ3F1150_guided,SQ3F1150_DeNovo,SQ3F1150_AbInitio, ncol=6, rel_widths = c(3.5,3.5,3.5,6,6,6))
#pdf 12x15 inches (landscape)


#sub40k - Average
inpt40avg <- melt(subset(Sub40k, Evaluator == "Average"),id.vars=c("Dataset","Assembly","Method","Tool","Evaluator"))
inpt40avg$Dataset <- factor(inpt40avg$Dataset, levels=c("LSK114_SIRVs","LSK114_sequins"))

Prec40avg <- subset(inpt40avg,variable=="Precision")
Rec40avg <- subset(inpt40avg,variable=="Sensitivity")
F140avg <- subset(inpt40avg,variable=="F1")
Prec40_DNavg <- subset(Prec40avg,Method=="De novo" | Method=="RawReads")
Prec40_Gavg <- subset(Prec40avg,Method=="Guided" | Method=="RawReads")
Prec40_AIavg <- subset(Prec40avg,Method=="Ab initio" | Method=="RawReads")
Rec40_DNavg <- subset(Rec40avg,Method=="De novo" | Method=="RawReads")
Rec40_Gavg <- subset(Rec40avg,Method=="Guided" | Method=="RawReads")
Rec40_AIavg <- subset(Rec40avg,Method=="Ab initio" | Method=="RawReads")
F140_DNavg <- subset(F140avg,Method=="De novo" | Method=="RawReads")
F140_Gavg <- subset(F140avg,Method=="Guided" | Method=="RawReads")
F140_AIavg <- subset(F140avg,Method=="Ab initio" | Method=="RawReads")

Prec40_guidedavg <- ggplot(Prec40_Gavg, aes(fill=Tool, x=Dataset, y=value, group=Assembly)) + geom_point(aes(colour = Tool, shape = Method)) + geom_line(aes(colour = Tool, linetype = Assembly), data = ~ subset(., Assembly != "TALON_reco")) + geom_line(aes(colour = Tool, linetype = Assembly), data = ~ subset(., Assembly == "TALON_reco")) +  scale_linetype_manual(values = c("Control"="solid","Bambu" = "solid", "FLAIR" = "solid", "isoQuant" = "solid", "TALON" = "solid", "FLAMES" = "solid", "Mandalorion" = "solid", "Stringtie2" = "solid", "TALON_reco" = "longdash")) + ylim(0,1) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = c("Bambu" = "brown","FLAIR"="violet","isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","RATTLE"="springgreen2","RNAbloom"="coral2","RNAbloom2"="orangered3","Stringtie2"="palegreen4","TALON"="wheat2","FLAMES"="blue2","Mandalorion"="darkgoldenrod1"))  + scale_shape_manual(values=c(15,9)) + xlab("") + ylab("Precision")
Prec40_DeNovoavg <- ggplot(Prec40_DNavg, aes(fill=Tool, x=Dataset, y=value, group=Assembly)) + geom_point(aes(colour = Tool, shape = Method)) + geom_line(aes(colour = Tool)) +  ylim(0,1) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = c("Bambu" = "brown","FLAIR"="violet","isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","RATTLE"="springgreen2","RNAbloom"="coral2","RNAbloom2"="orangered3","Stringtie2"="palegreen4","TALON"="wheat2","FLAMES"="blue2","Mandalorion"="darkgoldenrod1")) + scale_shape_manual(values=c(17,9)) + xlab("") + ylab("Precision")
Prec40_AbInitioavg <- ggplot(Prec40_AIavg, aes(fill=Tool, x=Dataset, y=value, group=Assembly)) + geom_point(aes(colour = Tool, shape = Method)) + geom_line(aes(colour = Tool)) +  ylim(0,1) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = c("Bambu" = "brown","FLAIR"="violet","isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","RATTLE"="springgreen2","RNAbloom"="coral2","RNAbloom2"="orangered3","Stringtie2"="palegreen4","TALON"="wheat2","FLAMES"="blue2","Mandalorion"="darkgoldenrod1")) + scale_shape_manual(values=c(19,9)) + xlab("") + ylab("Precision")

Rec40_guidedavg <- ggplot(Rec40_Gavg, aes(fill=Tool, x=Dataset, y=value, group=Assembly)) + geom_point(aes(colour = Tool, shape = Method)) + geom_line(aes(colour = Tool, linetype = Assembly), data = ~ subset(., Assembly != "TALON_reco")) + geom_line(aes(colour = Tool, linetype = Assembly), data = ~ subset(., Assembly == "TALON_reco")) +  scale_linetype_manual(values = c("Control"="solid","Bambu" = "solid", "FLAIR" = "solid", "isoQuant" = "solid", "TALON" = "solid", "FLAMES" = "solid", "Mandalorion" = "solid", "Stringtie2" = "solid", "TALON_reco" = "longdash")) +  ylim(0,1) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = c("Bambu" = "brown","FLAIR"="violet","isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","RATTLE"="springgreen2","RNAbloom"="coral2","RNAbloom2"="orangered3","Stringtie2"="palegreen4","TALON"="wheat2","FLAMES"="blue2","Mandalorion"="darkgoldenrod1")) + scale_shape_manual(values=c(15,9)) + xlab("") + ylab("Sensitivity")
Rec40_DeNovoavg <- ggplot(Rec40_DNavg, aes(fill=Tool, x=Dataset, y=value, group=Assembly)) + geom_point(aes(colour = Tool, shape = Method)) + geom_line(aes(colour = Tool)) +  ylim(0,1) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = c("Bambu" = "brown","FLAIR"="violet","isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","RATTLE"="springgreen2","RNAbloom"="coral2","RNAbloom2"="orangered3","Stringtie2"="palegreen4","TALON"="wheat2","FLAMES"="blue2","Mandalorion"="darkgoldenrod1")) + scale_shape_manual(values=c(17,9)) + xlab("") + ylab("Sensitivity")
Rec40_AbInitioavg <- ggplot(Rec40_AIavg, aes(fill=Tool, x=Dataset, y=value, group=Assembly)) + geom_point(aes(colour = Tool, shape = Method)) + geom_line(aes(colour = Tool)) +  ylim(0,1) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = c("Bambu" = "brown","FLAIR"="violet","isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","RATTLE"="springgreen2","RNAbloom"="coral2","RNAbloom2"="orangered3","Stringtie2"="palegreen4","TALON"="wheat2","FLAMES"="blue2","Mandalorion"="darkgoldenrod1")) + scale_shape_manual(values=c(19,9)) + xlab("") + ylab("Sensitivity")

F140_guidedavg <- ggplot(F140_Gavg, aes(fill=Tool, x=Dataset, y=value, group=Assembly)) + geom_point(aes(colour = Tool, shape = Method)) + geom_line(aes(colour = Tool, linetype = Assembly), data = ~ subset(., Assembly != "TALON_reco")) + geom_line(aes(colour = Tool, linetype = Assembly), data = ~ subset(., Assembly == "TALON_reco")) +  scale_linetype_manual(values = c("Control"="solid","Bambu" = "solid", "FLAIR" = "solid", "isoQuant" = "solid", "TALON" = "solid", "FLAMES" = "solid", "Mandalorion" = "solid", "Stringtie2" = "solid", "TALON_reco" = "longdash")) +  ylim(0,1) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = c("Bambu" = "brown","FLAIR"="violet","isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","RATTLE"="springgreen2","RNAbloom"="coral2","RNAbloom2"="orangered3","Stringtie2"="palegreen4","TALON"="wheat2","FLAMES"="blue2","Mandalorion"="darkgoldenrod1")) + scale_shape_manual(values=c(15,9)) + xlab("") + ylab("F1")
F140_DeNovoavg <- ggplot(F140_DNavg, aes(fill=Tool, x=Dataset, y=value, group=Assembly)) + geom_point(aes(colour = Tool, shape = Method)) + geom_line(aes(colour = Tool)) +  ylim(0,1) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = c("Bambu" = "brown","FLAIR"="violet","isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","RATTLE"="springgreen2","RNAbloom"="coral2","RNAbloom2"="orangered3","Stringtie2"="palegreen4","TALON"="wheat2","FLAMES"="blue2","Mandalorion"="darkgoldenrod1")) + scale_shape_manual(values=c(17,9)) + xlab("") + ylab("F1")
F140_AbInitioavg <- ggplot(F140_AIavg, aes(fill=Tool, x=Dataset, y=value, group=Assembly)) + geom_point(aes(colour = Tool, shape = Method)) + geom_line(aes(colour = Tool)) +  ylim(0,1) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = c("Bambu" = "brown","FLAIR"="violet","isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","RATTLE"="springgreen2","RNAbloom"="coral2","RNAbloom2"="orangered3","Stringtie2"="palegreen4","TALON"="wheat2","FLAMES"="blue2","Mandalorion"="darkgoldenrod1")) + scale_shape_manual(values=c(19,9)) + xlab("") + ylab("F1")

Prec40_DeNovoavg <- Prec40_DeNovoavg + theme(legend.position = "none")
Prec40_guidedavg <- Prec40_guidedavg + theme(legend.position = "none")
Prec40_AbInitioavg <- Prec40_AbInitioavg + theme(legend.position = "none")
Rec40_DeNovoavg <- Rec40_DeNovoavg + theme(legend.position = "none")
Rec40_guidedavg <- Rec40_guidedavg + theme(legend.position = "none")
Rec40_AbInitioavg <- Rec40_AbInitioavg + theme(legend.position = "none")
F140_DeNovoavg <- F140_DeNovoavg + theme(legend.position = "none")
F140_guidedavg <- F140_guidedavg + theme(legend.position = "none")
F140_AbInitioavg <- F140_AbInitioavg + theme(legend.position = "none")

#sub150k - Average
inpt150avg <- melt(subset(Sub150k, Evaluator == "Average"),id.vars=c("Dataset","Assembly","Method","Tool","Evaluator"))
inpt150avg$Dataset <- factor(inpt150avg$Dataset, levels=c("LSK109_sequins","LSK114_sequins","RNA002_sequins","RNA004_sequins"))

Prec150avg <- subset(inpt150avg,variable=="Precision")
Rec150avg <- subset(inpt150avg,variable=="Sensitivity")
F1150avg <- subset(inpt150avg,variable=="F1")
Prec150_DNavg <- subset(Prec150avg,Method=="De novo" | Method=="RawReads")
Prec150_Gavg <- subset(Prec150avg,Method=="Guided" | Method=="RawReads")
Prec150_AIavg <- subset(Prec150avg,Method=="Ab initio" | Method=="RawReads")
Rec150_DNavg <- subset(Rec150avg,Method=="De novo" | Method=="RawReads")
Rec150_Gavg <- subset(Rec150avg,Method=="Guided" | Method=="RawReads")
Rec150_AIavg <- subset(Rec150avg,Method=="Ab initio" | Method=="RawReads")
F1150_DNavg <- subset(F1150avg,Method=="De novo" | Method=="RawReads")
F1150_Gavg <- subset(F1150avg,Method=="Guided" | Method=="RawReads")
F1150_AIavg <- subset(F1150avg,Method=="Ab initio" | Method=="RawReads")

Prec150_guidedavg <- ggplot(Prec150_Gavg, aes(fill=Tool, x=Dataset, y=value, group=Assembly)) + geom_point(aes(colour = Tool, shape = Method)) + geom_line(aes(colour = Tool, linetype = Assembly), data = ~ subset(., Assembly != "TALON_reco")) + geom_line(aes(colour = Tool, linetype = Assembly), data = ~ subset(., Assembly == "TALON_reco")) +  scale_linetype_manual(values = c("Control"="solid","Bambu" = "solid", "FLAIR" = "solid", "isoQuant" = "solid", "TALON" = "solid", "FLAMES" = "solid", "Mandalorion" = "solid", "Stringtie2" = "solid", "TALON_reco" = "longdash")) +  ylim(0,1) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = c("Bambu" = "brown","FLAIR"="violet","isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","RATTLE"="springgreen2","RNAbloom"="coral2","RNAbloom2"="orangered3","Stringtie2"="palegreen4","TALON"="wheat2","FLAMES"="blue2","Mandalorion"="darkgoldenrod1")) + scale_shape_manual(values=c(15,9)) + xlab("") + ylab("Precision")
Prec150_DeNovoavg <- ggplot(Prec150_DNavg, aes(fill=Tool, x=Dataset, y=value, group=Assembly)) + geom_point(aes(colour = Tool, shape = Method)) + geom_line(aes(colour = Tool)) +  ylim(0,1) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = c("Bambu" = "brown","FLAIR"="violet","isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","RATTLE"="springgreen2","RNAbloom"="coral2","RNAbloom2"="orangered3","Stringtie2"="palegreen4","TALON"="wheat2","FLAMES"="blue2","Mandalorion"="darkgoldenrod1")) + scale_shape_manual(values=c(17,9)) + xlab("") + ylab("Precision")
Prec150_AbInitioavg <- ggplot(Prec150_AIavg, aes(fill=Tool, x=Dataset, y=value, group=Assembly)) + geom_point(aes(colour = Tool, shape = Method)) + geom_line(aes(colour = Tool)) +  ylim(0,1) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = c("Bambu" = "brown","FLAIR"="violet","isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","RATTLE"="springgreen2","RNAbloom"="coral2","RNAbloom2"="orangered3","Stringtie2"="palegreen4","TALON"="wheat2","FLAMES"="blue2","Mandalorion"="darkgoldenrod1")) + scale_shape_manual(values=c(19,9)) + xlab("") + ylab("Precision")

Rec150_guidedavg <- ggplot(Rec150_Gavg, aes(fill=Tool, x=Dataset, y=value, group=Assembly)) + geom_point(aes(colour = Tool, shape = Method)) + geom_line(aes(colour = Tool, linetype = Assembly), data = ~ subset(., Assembly != "TALON_reco")) + geom_line(aes(colour = Tool, linetype = Assembly), data = ~ subset(., Assembly == "TALON_reco")) +  scale_linetype_manual(values = c("Control"="solid","Bambu" = "solid", "FLAIR" = "solid", "isoQuant" = "solid", "TALON" = "solid", "FLAMES" = "solid", "Mandalorion" = "solid", "Stringtie2" = "solid", "TALON_reco" = "longdash")) +  ylim(0,1) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = c("Bambu" = "brown","FLAIR"="violet","isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","RATTLE"="springgreen2","RNAbloom"="coral2","RNAbloom2"="orangered3","Stringtie2"="palegreen4","TALON"="wheat2","FLAMES"="blue2","Mandalorion"="darkgoldenrod1")) + scale_shape_manual(values=c(15,9)) + xlab("") + ylab("Sensitivity")
Rec150_DeNovoavg <- ggplot(Rec150_DNavg, aes(fill=Tool, x=Dataset, y=value, group=Assembly)) + geom_point(aes(colour = Tool, shape = Method)) + geom_line(aes(colour = Tool)) +  ylim(0,1) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = c("Bambu" = "brown","FLAIR"="violet","isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","RATTLE"="springgreen2","RNAbloom"="coral2","RNAbloom2"="orangered3","Stringtie2"="palegreen4","TALON"="wheat2","FLAMES"="blue2","Mandalorion"="darkgoldenrod1")) + scale_shape_manual(values=c(17,9)) + xlab("") + ylab("Sensitivity")
Rec150_AbInitioavg <- ggplot(Rec150_AIavg, aes(fill=Tool, x=Dataset, y=value, group=Assembly)) + geom_point(aes(colour = Tool, shape = Method)) + geom_line(aes(colour = Tool)) +  ylim(0,1) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = c("Bambu" = "brown","FLAIR"="violet","isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","RATTLE"="springgreen2","RNAbloom"="coral2","RNAbloom2"="orangered3","Stringtie2"="palegreen4","TALON"="wheat2","FLAMES"="blue2","Mandalorion"="darkgoldenrod1")) + scale_shape_manual(values=c(19,9)) + xlab("") + ylab("Sensitivity")

F1150_guidedavg <- ggplot(F1150_Gavg, aes(fill=Tool, x=Dataset, y=value, group=Assembly)) + geom_point(aes(colour = Tool, shape = Method)) + geom_line(aes(colour = Tool, linetype = Assembly), data = ~ subset(., Assembly != "TALON_reco")) + geom_line(aes(colour = Tool, linetype = Assembly), data = ~ subset(., Assembly == "TALON_reco")) +  scale_linetype_manual(values = c("Control"="solid","Bambu" = "solid", "FLAIR" = "solid", "isoQuant" = "solid", "TALON" = "solid", "FLAMES" = "solid", "Mandalorion" = "solid", "Stringtie2" = "solid", "TALON_reco" = "longdash")) +  ylim(0,1) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = c("Bambu" = "brown","FLAIR"="violet","isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","RATTLE"="springgreen2","RNAbloom"="coral2","RNAbloom2"="orangered3","Stringtie2"="palegreen4","TALON"="wheat2","FLAMES"="blue2","Mandalorion"="darkgoldenrod1")) + scale_shape_manual(values=c(15,9)) + xlab("") + ylab("F1")
F1150_DeNovoavg <- ggplot(F1150_DNavg, aes(fill=Tool, x=Dataset, y=value, group=Assembly)) + geom_point(aes(colour = Tool, shape = Method)) + geom_line(aes(colour = Tool)) +  ylim(0,1) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = c("Bambu" = "brown","FLAIR"="violet","isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","RATTLE"="springgreen2","RNAbloom"="coral2","RNAbloom2"="orangered3","Stringtie2"="palegreen4","TALON"="wheat2","FLAMES"="blue2","Mandalorion"="darkgoldenrod1")) + scale_shape_manual(values=c(17,9)) + xlab("") + ylab("F1")
F1150_AbInitioavg <- ggplot(F1150_AIavg, aes(fill=Tool, x=Dataset, y=value, group=Assembly)) + geom_point(aes(colour = Tool, shape = Method)) + geom_line(aes(colour = Tool)) +  ylim(0,1) + theme_bw() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + scale_color_manual(values = c("Bambu" = "brown","FLAIR"="violet","isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","RATTLE"="springgreen2","RNAbloom"="coral2","RNAbloom2"="orangered3","Stringtie2"="palegreen4","TALON"="wheat2","FLAMES"="blue2","Mandalorion"="darkgoldenrod1")) + scale_shape_manual(values=c(19,9)) + xlab("") + ylab("F1")

Prec150_DeNovoavg <- Prec150_DeNovoavg + theme(legend.position = "none")
Prec150_guidedavg <- Prec150_guidedavg + theme(legend.position = "none")
Prec150_AbInitioavg <- Prec150_AbInitioavg + theme(legend.position = "none")
Rec150_DeNovoavg <- Rec150_DeNovoavg + theme(legend.position = "none")
Rec150_guidedavg <- Rec150_guidedavg + theme(legend.position = "none")
Rec150_AbInitioavg <- Rec150_AbInitioavg + theme(legend.position = "none")
F1150_DeNovoavg <- F1150_DeNovoavg + theme(legend.position = "none")
F1150_guidedavg <- F1150_guidedavg + theme(legend.position = "none")
F1150_AbInitioavg <- F1150_AbInitioavg + theme(legend.position = "none")

#Main figure
plot_grid(Prec40_guidedavg,Prec40_DeNovoavg,Prec40_AbInitioavg,Prec150_guidedavg,Prec150_DeNovoavg,Prec150_AbInitioavg,Rec40_guidedavg,Rec40_DeNovoavg,Rec40_AbInitioavg,Rec150_guidedavg,Rec150_DeNovoavg,Rec150_AbInitioavg,F140_guidedavg,F140_DeNovoavg,F140_AbInitioavg,F1150_guidedavg,F1150_DeNovoavg,F1150_AbInitioavg, ncol=6, rel_widths = c(3.5,3.5,3.5,6,6,6))
#pdf 12x7.5 inches (landscape)