library(ggplot2)
TPFP <- read.csv("GFF-PrecisionSensitivity.csv", sep=",", header=T)
TPFP$Sensitivity <- TPFP$TP / (TPFP$TP + TPFP$FN )
TPFP$Precision <- TPFP$TP / (TPFP$TP + TPFP$FP )

Guided <- subset(TPFP, Method=="Guided")
DeNovo <- subset(TPFP, Method=="De novo")
AbInitio <- subset(TPFP, Method=="Ab initio")

Gd <- ggplot(Guided, aes(fill=Tool,x=Precision, y=Sensitivity, label=Subset)) + geom_point(aes(colour = Tool)) + xlim(0,1) + ylim(0,1) + theme_bw() + scale_color_manual(values = c("Bambu" = "brown", "isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","Stringtie2"="palegreen4"))
DN <- ggplot(DeNovo, aes(fill=Tool,x=Precision, y=Sensitivity, label=Subset)) + geom_point(aes(colour = Tool)) + xlim(0,1) + ylim(0,1) + theme_bw() + scale_color_manual(values = c("Bambu" = "brown", "isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","Stringtie2"="palegreen4"))
AI <- ggplot(AbInitio, aes(fill=Tool,x=Precision, y=Sensitivity, label=Subset)) + geom_point(aes(colour = Tool)) + xlim(0,1) + ylim(0,1) + theme_bw() + scale_color_manual(values = c("Bambu" = "brown", "isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","Stringtie2"="palegreen4"))

ledg1 <- get_legend(Gd)
ledg2 <- get_legend(DN)
ledg3 <- get_legend(AI)
legend <- plot_grid(ledg1,ledg3, ncol = 1)

SQTPFP <- read.csv("SQ3-PrecisionSensitivity.csv", sep=",", header=T)
SQTPFP$Sensitivity <- SQTPFP$TP / (SQTPFP$TP + SQTPFP$FN )
SQTPFP$Precision <- SQTPFP$TP / (SQTPFP$TP + SQTPFP$FP )
SQGuided <- subset(SQTPFP, Method=="Guided")
SQDeNovo <- subset(SQTPFP, Method=="De novo")
SQAbInitio <- subset(SQTPFP, Method=="Ab initio")
SQGd <- ggplot(SQGuided, aes(fill=Tool,x=Precision, y=Sensitivity, label=Subset)) + geom_point(aes(colour = Tool)) + xlim(0,1) + ylim(0,1) + theme_bw() + scale_color_manual(values = c("Bambu" = "brown", "isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","Stringtie2"="palegreen4"))
SQDN <- ggplot(SQDeNovo, aes(fill=Tool,x=Precision, y=Sensitivity, label=Subset)) + geom_point(aes(colour = Tool)) + xlim(0,1) + ylim(0,1) + theme_bw() + scale_color_manual(values = c("Bambu" = "brown", "isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","Stringtie2"="palegreen4"))
SQAI <- ggplot(SQAbInitio, aes(fill=Tool,x=Precision, y=Sensitivity, label=Subset)) + geom_point(aes(colour = Tool)) + xlim(0,1) + ylim(0,1) + theme_bw() + scale_color_manual(values = c("Bambu" = "brown", "isONclust"="mediumpurple1","isONclust2"="purple","isoQuant"="turquoise2","Stringtie2"="palegreen4"))

Gd <- Gd + theme(legend.position = "none")
SQGd <- SQGd + theme(legend.position = "none")
DN <- DN + theme(legend.position = "none")
SQDN <- SQDN + theme(legend.position = "none")
AI <- AI + theme(legend.position = "none")
SQAI <- SQAI + theme(legend.position = "none")

pdf(file = "Depth-Allsets.pdf", width = 9, height=4.92)
plot_grid(Gd,DN,AI,legend,SQGd,SQDN,SQAI,legend,nrow=2,rel_widths = c(6,6,6,3))
dev.off()
